# Generated by Django 6.0.4 on 2026-04-23 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='trust_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulatorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributorprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distributorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='accreditation_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='accreditation_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='lab_type',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='pharmacy_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('HOSPITAL', 'Hospital')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regulatorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('LAB', 'Lab'), ('REGULATOR', 'Regulator'), ('DISTRIBUTOR', 'Distributor'), ('PHARMACY', 'Pharmacy'), ('ADMIN', 'Admin')], default='PHARMACY', max_length=55),
        ),
    ]
