# Generated by Django 6.0.4 on 2026-06-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_distributorprofile_created_at_labprofile_created_at_and_more'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', ' Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='labs.labreport')),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounts.regulatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
