# Generated by Django 6.0.4 on 2026-04-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_distributorprofile_created_at_labprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('composition', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_type', models.CharField(choices=[('STRIP', 'Strip'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('BOX', 'Box'), ('TUBE', 'Tube')], max_length=50)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INHALER', 'Inhaler')], max_length=50)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.manufacturerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('IN_PRODUCTION', 'In Production'), ('LAB_TESTING', 'Lab Testing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISTRIBUTED', 'Distributed')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.manufacturerprofile')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
