# Generated by Django 6.0.4 on 2026-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('IN_PRODUCTION', 'In Production'), ('LAB_TESTING', 'Lab Testing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISTRIBUTED', 'Distributed')], default='IN_PRODUCTION', max_length=255),
        ),
    ]
