# Generated by Django 6.0.4 on 2026-04-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_distributorprofile_created_at_labprofile_created_at_and_more'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INCONCLUSIVE', 'Inconclusive')], max_length=50)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=50)),
                ('report_files', models.FileField(blank=True, null=True, upload_to='labs/lab_reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='medicines.batch')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='accounts.labprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
